[pytest]

# Nơi chứa các file test
testpaths = tests

# Gợi ý định dạng tên file test
python_files = test_*.py

# Để hỗ trợ async def test_* mà không cần thêm @pytest.mark.asyncio
asyncio_mode = auto

# Định nghĩa marker nếu có dùng
markers =
    asyncio: mark test as asyncio
